OUT-66 | Profile Manager Fixes
copilot-platforms/profile-manager pull request #2
Opened 2024-02-19 14:39 UTC by rrojan

Ref: [Linear](https://linear.app/copilotplatforms/issue/OUT-71/sidebar-custom-field-order-should-be-based-on-the-order-field)

Changes:
- Order custom fields on the basis of `order` key
- When iconImageUrl is not provided default to fallbackIconColor

2024-02-21 11:01 UTC, sazanrjb requested changes

2024-02-21 11:01 UTC, sazanrjb commented on src/lib/db.ts
> +  private static async disconnectAndExit(): Promise<void> {
:+1:

2024-02-22 00:27 UTC, rrojan commented on src/app/manage/views/ManagePageContainer.tsx
>            result[key] = obj[key];
I reverted the changes and forgot to remove the comment. Will remove this.

2024-02-22 08:55 UTC, rrojan commented on src/app/api/client-profile-updates/services/clientProfileUpdates.service.ts
> -      LIMIT 5;
@sazanrjb I think what I implemented does the same thing.

When the results are `LIMIT 4` but the number of items being returned is less than 4  i.e. `parsedUpdateHistory.length < 4` then the oldest value should be empty

2024-02-22 12:26 UTC, sazanrjb commented on src/app/api/client-profile-updates/services/clientProfileUpdates.service.ts
> -      LIMIT 5;
but it will fetch the latest 4 histories, what if there are more than 4 in db?

2024-02-22 12:27 UTC, rrojan commented on src/app/api/profile-update-history/route.ts
> +    if (parsedUpdateHistory.length < 4) {
@sazanrjb With `LIMIT 4` being implemented, if the number of items returned is less than 4 then the starting value should be empty. Checking for the oldest empty value and returning those results, and performing a length check like above should yield the same result.

Maybe I'm misunderstanding the problem mentioned in the issue so please correct me if I'm looking at this from another angle :pray:

2024-02-22 13:12 UTC, merged